name: Build lsfg-vk on Fedora
on:
  push:
    branches: ["feat/config"]


jobs:
  build-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Prepare cache for dnf packages
      uses: actions/cache@v4
      with:
        path: /var/cache/libdnf5
        key: fedora-dnf-cache
    - name: Install build dependencies
      run: |
        echo "keepcache=1" >> /etc/dnf/dnf.conf
        dnf update -y
        dnf install -y \
          git \
          clang llvm \
          cmake ninja-build \
          spirv-headers-devel vulkan-headers vulkan-loader-devel
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Configure with CMake and Ninja
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=./build-release
    - name: Build with Ninja
      run: |
        ninja -C build
    - name: Install with CMake
      run: |
        cmake --install build
    - name: Upload lsfg-vk artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsfg-vk_fedora
        path: |
          build-release/share/vulkan/implicit_layer.d/VkLayer_LS_frame_generation.json
          build-release/lib/liblsfg-vk.so
